# 1. Disparity (group-wise): highest and lowest  (For HeatMap figure)

In [34]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
models = ['original', 'gamma_2', 'adasyn', 'smote', 'oversampling',  'undersampling', 'nearmiss1', 'nearmiss3', 'distant']


metric_idx = 13 #F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13
evaluation = "relative_disparity" # "relative_disparity" or "absolute_disparity"

In [35]:
full_list = []
for mod in models:
    model_path = r"csv_files/"+ mod + "/test/"



    # take the csv files in that directory
    if 'dp' in mod:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result_temp_test_isotonic*.csv')]
    else:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
    print(files)
    
    df = pd.read_csv(model_path  + files[0])
    
    #full_list.append(list(df.loc[4:6]))
    values = df.iloc[7:,metric_idx]  #3:7 -- ethnicity ; 7: --> age ; 1:3 --> gender
    print(values)
    if evaluation == "relative_disparity":
        disparity = max(list(values)) / min(list(values))
    elif evaluation== "absolute_disparity":
        disparity = max(list(values)) - min(list(values))
    else:
        print("Error")
        break
        
    
    print(disparity)
    full_list.append(disparity)
    

df_full = pd.DataFrame(full_list)

['1_AVERAGE.csv']
7     0.185333
8     0.377000
9     0.321000
10    0.475667
11    0.411333
12    0.421667
13    0.432333
14    0.277000
Name: MCC, dtype: float64
2.5665467625899288
['1_AVERAGE.csv']
7     0.163333
8     0.414333
9     0.340333
10    0.480000
11    0.448667
12    0.418000
13    0.435000
14    0.257000
Name: MCC, dtype: float64
2.9387755102040822
['1_AVERAGE.csv']
7     0.184667
8     0.442667
9     0.308333
10    0.419000
11    0.353000
12    0.367333
13    0.390333
14    0.246667
Name: MCC, dtype: float64
2.397111913357402
['1_AVERAGE.csv']
7     0.213333
8     0.375333
9     0.335000
10    0.464667
11    0.398667
12    0.362000
13    0.377000
14    0.224333
Name: MCC, dtype: float64
2.178125
['1_AVERAGE.csv']
7     0.242333
8     0.369333
9     0.366000
10    0.457667
11    0.415667
12    0.396333
13    0.427000
14    0.351667
Name: MCC, dtype: float64
1.8885832187070153
['1_AVERAGE.csv']
7     0.201000
8     0.341667
9     0.316000
10    0.422000
11    0.389333
12    0.428000
13    0.397333
14    0.231000
Name: MCC, dtype: float64
2.1293532338308467
['1_AVERAGE.csv']
7     0.102000
8     0.245667
9     0.223333
10    0.298333
11    0.242667
12    0.322667
13    0.307000
14    0.213667
Name: MCC, dtype: float64
3.163398692810457
['1_AVERAGE.csv']
7     0.107667
8     0.270667
9     0.299000
10    0.360000
11    0.297667
12    0.355667
13    0.344667
14    0.212333
Name: MCC, dtype: float64
3.3436532507739956
['1_AVERAGE.csv']
7     0.182667
8     0.270333
9     0.173667
10    0.208333
11    0.243667
12    0.279667
13    0.291333
14    0.240667
Name: MCC, dtype: float64
1.6775431861804224

In [36]:
# printing one row of result 
# For example, the absoute disparity results from all 9 sampling (showing in row). 
# (0,0) represents original model disparity among one group (age, gender, race). If asian has highest F1 score and black has lowest F1 score, then absolute disparity is (Asian F1 - Black F1) 
df_full

          0
0  2.566547
1  2.938776
2  2.397112
3  2.178125
4  1.888583
5  2.129353
6  3.163399
7  3.343653
8  1.677543

### DP relative disparity findout race

In [32]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
models = ['dp_white_1', 'dp_black_avg', 'dp_hispanic_1', 'dp_asian_1']

# change here
metric_idx = 13 #F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13
evaluation = "relative_disparity" # "relative_disparity" or "absolute_disparity"

In [33]:
full_list = []
val = 3
for mod in models:
    model_path = r"csv_files/"+ mod + "/test/"

    # take the csv files in that directory
    if 'avg' not in mod:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result_temp_test_isotonic*.csv')]
    else:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
    print(files)
    
    df = pd.read_csv(model_path  + files[0])
    
    #full_list.append(list(df.loc[4:6]))
    print(df.iloc[val,0])
    values = df.iloc[val,metric_idx]
    print(df.iloc[val,metric_idx])
    full_list.append(values)
    val = val+1
    


disparity = max(list(full_list)) / min(list(full_list))
print(disparity)

['result_temp_test_isotonic_8.csv']
White
0.377
['1_AVERAGE.csv']
Black
0.384
['result_temp_test_isotonic_5.csv']
Hispanic
0.487
['result_temp_test_isotonic_4.csv']
Asian
0.424
1.2917771883289124

### DP relative disparity findout age

In [37]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
#models = ['dp_age30_1', 'dp_age4050_1', 'dp_age8090_1']
models = ['dp_age4050_1', 'dp_age8090_1', 'dp_age90_avg']

# change here
metric_idx = 13 #F1_C1 = 8 ; Rec_C1 = 6 ; bal_acc = 3; MCC = 13
evaluation = "relative_disparity" # "relative_disparity" or "absolute_disparity"

In [38]:
full_list = []
#val = [7,9,13] 
val = [9,13,14] 
i=0
for mod in models:
    model_path = r"csv_files/"+ mod + "/test/"

    # take the csv files in that directory
    if 'avg' not in mod:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result_temp_test_isotonic*.csv')]
    else:
        files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
    print(files)
    
    df = pd.read_csv(model_path  + files[0])
    
    #full_list.append(list(df.loc[4:6]))
    print(df.iloc[val[i],0])
    values = df.iloc[val[i],metric_idx]
    print(df.iloc[val[i],metric_idx])
    full_list.append(values)
    i = i+1
    


disparity = max(list(full_list)) / min(list(full_list))
print(disparity)

['result_temp_test_isotonic_8.csv']
Age [40, 50)
0.37
['result_temp_test_isotonic_7.csv']
Age [80, 90)
0.434
['1_AVERAGE.csv']
Age >= 90
0.319
1.3605015673981191

# Original and Sampling

In [40]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
models = ['original', 'undersampling', 'nearmiss1', 'nearmiss3', 'distant', 'oversampling', 'smote', 'adasyn', 'gamma_2']


metric_idx = 5 # F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13
#evaluation = "absolute_disparity" # "relative_disparity" or "absolute_disparity"

In [41]:
full_list = []
for mod in models:
    model_path = r"csv_files/"+ mod + "/test/"


    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
    # take the csv files in that directory
#     if 'dp' in mod:
#         files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result_temp_test_isotonic*.csv')]
#     else:
#         files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
    print(files)
    
    df = pd.read_csv(model_path  + files[0])
    
    #full_list.append(list(df.loc[4:6]))
    values = df.iloc[:,metric_idx]  #3:7 -- ethnicity ; 7: --> age ; 1:3 --> gender
    print(values)
#     if evaluation == "relative_disparity":
#         disparity = max(list(values)) / min(list(values))
#     elif evaluation== "absolute_disparity":
#         disparity = max(list(values)) - min(list(values))
#     else:
#         print("Error")
#         break
        
    
#     print(disparity)
    full_list.append(list(values))
    

df_full = pd.DataFrame(full_list)

['1_AVERAGE.csv']
0     0.476667
1     0.474333
2     0.479333
3     0.461000
4     0.390000
5     0.483333
6     0.443000
7     0.153667
8     0.432333
9     0.396333
10    0.507333
11    0.463000
12    0.500000
13    0.528333
14    0.457333
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.454667
1     0.448667
2     0.461333
3     0.439333
4     0.331667
5     0.421667
6     0.484667
7     0.152000
8     0.394333
9     0.387000
10    0.453333
11    0.439000
12    0.504667
13    0.501000
14    0.437667
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.356000
1     0.330667
2     0.387333
3     0.359000
4     0.198667
5     0.276000
6     0.384667
7     0.077333
8     0.305333
9     0.307000
10    0.333667
11    0.300000
12    0.411000
13    0.429000
14    0.427333
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.396333
1     0.389000
2     0.406000
3     0.386333
4     0.260333
5     0.383000
6     0.432667
7     0.088000
8     0.330667
9     0.373667
10    0.393000
11    0.354667
12    0.445333
13    0.458667
14    0.410333
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.343000
1     0.340667
2     0.345000
3     0.338667
4     0.255333
5     0.102667
6     0.425000
7     0.137000
8     0.339667
9     0.273667
10    0.283333
11    0.320667
12    0.376667
13    0.407667
14    0.405667
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.478667
1     0.484333
2     0.472333
3     0.466667
4     0.399000
5     0.484000
6     0.551000
7     0.194000
8     0.426667
9     0.434333
10    0.496333
11    0.468000
12    0.479000
13    0.523667
14    0.508667
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.450000
1     0.453667
2     0.446000
3     0.427000
4     0.395333
5     0.458667
6     0.511667
7     0.164333
8     0.424000
9     0.407667
10    0.496667
11    0.452333
12    0.452333
13    0.486333
14    0.425333
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.438667
1     0.436667
2     0.441000
3     0.421000
4     0.377000
5     0.415000
6     0.424333
7     0.139333
8     0.466000
9     0.382333
10    0.449000
11    0.404000
12    0.452333
13    0.493667
14    0.450667
Name: F1_C1, dtype: float64
['1_AVERAGE.csv']
0     0.481333
1     0.472333
2     0.490667
3     0.461667
4     0.401667
5     0.525333
6     0.504000
7     0.132667
8     0.455333
9     0.413000
10    0.512667
11    0.496667
12    0.497667
13    0.530333
14    0.443333
Name: F1_C1, dtype: float64

In [42]:
df_full.T

,0,1,2,3,4,5,6,7,8
0,0.476667,0.454667,0.356000,0.396333,0.343000,0.478667,0.450000,0.438667,0.481333
1,0.474333,0.448667,0.330667,0.389000,0.340667,0.484333,0.453667,0.436667,0.472333
2,0.479333,0.461333,0.387333,0.406000,0.345000,0.472333,0.446000,0.441000,0.490667
3,0.461000,0.439333,0.359000,0.386333,0.338667,0.466667,0.427000,0.421000,0.461667
4,0.390000,0.331667,0.198667,0.260333,0.255333,0.399000,0.395333,0.377000,0.401667
5,0.483333,0.421667,0.276000,0.383000,0.102667,0.484000,0.458667,0.415000,0.525333
6,0.443000,0.484667,0.384667,0.432667,0.425000,0.551000,0.511667,0.424333,0.504000
7,0.153667,0.152000,0.077333,0.088000,0.137000,0.194000,0.164333,0.139333,0.132667
8,0.432333,0.394333,0.305333,0.330667,0.339667,0.426667,0.424000,0.466000,0.455333
9,0.396333,0.387000,0.307000,0.373667,0.273667,0.434333,0.407667,0.382333,0.413000
10,0.507333,0.453333,0.333667,0.393000,0.283333,0.496333,0.496667,0.449000,0.512667
11,0.463000,0.439000,0.300000,0.354667,0.320667,0.468000,0.452333,0.404000,0.496667
12,0.500000,0.504667,0.411000,0.445333,0.376667,0.479000,0.452333,0.452333,0.497667
13,0.528333,0.501000,0.429000,0.458667,0.407667,0.523667,0.486333,0.493667,0.530333
14,0.457333,0.437667,0.427333,0.410333,0.405667,0.508667,0.425333,0.450667,0.443333

# Diff Graph

In [93]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
model_original = ['original']
model_black = ['dp_black_avg', 'undersampling', 'smote']
model_asian = ['dp_asian_avg', 'undersampling', 'smote']
model_30 = ['dp_age30_avg', 'undersampling', 'smote']
model_90 = ['dp_age90_avg', 'undersampling', 'smote']


metric_idx = 2 #F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13
#group = 4   # 4 -- black ; 6: asian; 7: age<30 ; 14 -- age>90
#evaluation = "absolute_disparity" # "relative_disparity" or "absolute_disparity"

#loading original
model_path_original = r"csv_files/original/test/"
files_original = [f for f in listdir(model_path_original) if fnmatch.fnmatch(f, '*AVERAGE*.csv')]
print(files_original)
df_original = pd.read_csv(model_path_original  + files_original[0])
df_original

['1_AVERAGE.csv']

,Group,Test_data,Recall_C1,Precision_C1,AUC_PR_C1,F1_C1,Recall_C0,Precision_C0,AUC_PR_C0,F1_C0,Accuracy,Balanced_Accuracy,AUC_ROC,MCC,FPR,FNR
0,whole,3236,0.609667,0.395000,0.481333,0.476667,0.875667,0.945000,0.976667,0.908667,0.845000,0.742667,0.855333,0.405333,0.012433,0.039000
1,Male,1797,0.592333,0.399333,0.489333,0.474333,0.888667,0.947000,0.981333,0.916667,0.856000,0.740000,0.870667,0.407000,0.011133,0.041000
2,female,1439,0.629000,0.390667,0.473333,0.479333,0.859667,0.943333,0.970667,0.899333,0.831000,0.744333,0.837000,0.403333,0.014033,0.037000
3,White,2324,0.593333,0.380667,0.463000,0.461000,0.874333,0.944000,0.977000,0.908000,0.842667,0.734000,0.851667,0.389000,0.012567,0.041000
4,Black,290,0.500000,0.326667,0.395000,0.390000,0.889667,0.944000,0.973667,0.915333,0.851667,0.694667,0.812333,0.322667,0.011033,0.049667
5,Hispanic,110,0.833333,0.342000,0.619333,0.483333,0.872667,0.985667,0.993667,0.925333,0.870000,0.853000,0.929000,0.480000,0.012733,0.016333
6,Asian,63,0.704000,0.324000,0.542000,0.443000,0.753000,0.938667,0.969667,0.835333,0.746000,0.728000,0.844333,0.346333,0.024700,0.029333
7,Age < 30,148,0.555667,0.089333,0.077000,0.153667,0.880667,0.989333,0.996333,0.931667,0.874000,0.718000,0.844000,0.185333,0.011933,0.044333
8,"Age [30, 40)",169,0.577667,0.347000,0.389333,0.432333,0.892000,0.955667,0.988000,0.922667,0.864000,0.735000,0.885667,0.377000,0.010800,0.042333
9,"Age [40, 50)",319,0.535333,0.317000,0.379667,0.396333,0.865000,0.941667,0.974333,0.901333,0.831000,0.700000,0.825000,0.321000,0.013500,0.046333
10,"Age [50, 60)",525,0.719333,0.396000,0.508667,0.507333,0.897333,0.972333,0.990333,0.933000,0.882333,0.808667,0.906667,0.475667,0.010267,0.027667
11,"Age [60, 70)",638,0.603333,0.379667,0.489333,0.463000,0.900000,0.958000,0.982667,0.928000,0.873000,0.752000,0.866667,0.411333,0.010000,0.039667
12,"Age [70, 80)",734,0.607000,0.430667,0.527000,0.500000,0.878000,0.937667,0.977667,0.906667,0.843000,0.742333,0.867000,0.421667,0.012200,0.039333
13,"Age [80, 90)",517,0.650333,0.449000,0.557000,0.528333,0.846333,0.928333,0.958000,0.885000,0.815333,0.748667,0.833667,0.432333,0.015367,0.034667
14,Age >= 90,186,0.507333,0.426333,0.485000,0.457333,0.783667,0.838333,0.897667,0.808667,0.718333,0.645667,0.730000,0.277000,0.021633,0.049000

In [94]:
all_list = []
full_list = []
for mod in model_black:
    print(mod)
    model_path = r"csv_files/"+ mod + "/test/"

    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result*.csv')]

    print(files)
    tempp_list = []
    tempp_list.append(mod)
    for file in files:
        df = pd.read_csv(model_path  + file)

        values = df.iloc[4,metric_idx]
        values_original = df_original.iloc[4,metric_idx]
        print(values-values_original)

    
        tempp_list.append(values-values_original)
    full_list.append(tempp_list)


print(full_list)

dp_black_avg
['result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_10.csv', 'result_temp_test_isotonic_8.csv']
0.14300000000000002
0.17900000000000005
0.25
undersampling
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
-0.035999999999999976
0.0
0.0
smote
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.0
0.03600000000000003
0.0
[['dp_black_avg', 0.14300000000000002, 0.17900000000000005, 0.25], ['undersampling', -0.035999999999999976, 0.0, 0.0], ['smote', 0.0, 0.03600000000000003, 0.0]]

In [95]:
for mod in model_asian:
    model_path = r"csv_files/"+ mod + "/test/"

    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result*.csv')]
    
    print(files)
    tempp_list = []
    tempp_list.append(mod)
    for file in files:
        df = pd.read_csv(model_path  + file)

        values = df.iloc[6,metric_idx]
        values_original = df_original.iloc[6,metric_idx]
        print(values-values_original)

        tempp_list.append(values-values_original)
    full_list.append(tempp_list)



print(full_list)

['result_temp_test_isotonic_1_2.csv', 'result_temp_test_isotonic_1_3.csv', 'result_temp_test_isotonic_4_1.csv']
0.07399999999999995
0.07399999999999995
0.07399999999999995
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.07399999999999995
0.18499999999999994
0.18499999999999994
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.07399999999999995
0.07399999999999995
0.18499999999999994
[['dp_black_avg', 0.14300000000000002, 0.17900000000000005, 0.25], ['undersampling', -0.035999999999999976, 0.0, 0.0], ['smote', 0.0, 0.03600000000000003, 0.0], ['dp_asian_avg', 0.07399999999999995, 0.07399999999999995, 0.07399999999999995], ['undersampling', 0.07399999999999995, 0.18499999999999994, 0.18499999999999994], ['smote', 0.07399999999999995, 0.07399999999999995, 0.18499999999999994]]

In [96]:
for mod in model_30:
    model_path = r"csv_files/"+ mod + "/test/"

    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result*.csv')]

    print(files)
    tempp_list = []
    tempp_list.append(mod)
    for file in files:
        df = pd.read_csv(model_path  + file)

        values = df.iloc[7,metric_idx]
        values_original = df_original.iloc[7,metric_idx]
        print(values-values_original)

        tempp_list.append(values-values_original)
    full_list.append(tempp_list)



print(full_list)

['result_temp_test_isotonic_1_1.csv', 'result_temp_test_isotonic_1_4.csv', 'result_temp_test_isotonic_1_4 - Copy.csv']
0.1113333333333334
0.1113333333333334
0.1113333333333334
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.1113333333333334
0.1113333333333334
0.1113333333333334
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.1113333333333334
0.1113333333333334
0.1113333333333334
[['dp_black_avg', 0.14300000000000002, 0.17900000000000005, 0.25], ['undersampling', -0.035999999999999976, 0.0, 0.0], ['smote', 0.0, 0.03600000000000003, 0.0], ['dp_asian_avg', 0.07399999999999995, 0.07399999999999995, 0.07399999999999995], ['undersampling', 0.07399999999999995, 0.18499999999999994, 0.18499999999999994], ['smote', 0.07399999999999995, 0.07399999999999995, 0.18499999999999994], ['dp_age30_avg', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334], ['undersampling', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334], ['smote', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334]]

In [97]:
for mod in model_90:
    model_path = r"csv_files/"+ mod + "/test/"

    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result*.csv')]

    print(files)
    tempp_list = []
    tempp_list.append(mod)
    for file in files:
        df = pd.read_csv(model_path  + file)

        values = df.iloc[14,metric_idx]
        values_original = df_original.iloc[14,metric_idx]
        print(values-values_original)

        tempp_list.append(values-values_original)
    full_list.append(tempp_list)

print(full_list)

['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_12.csv', 'result_temp_test_isotonic_2.csv']
0.17466666666666675
0.15166666666666673
0.1286666666666667
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
-0.007333333333333303
-0.030333333333333323
0.08366666666666667
['result_temp_test_isotonic_0.csv', 'result_temp_test_isotonic_1.csv', 'result_temp_test_isotonic_2.csv']
0.015666666666666718
-0.030333333333333323
-0.07533333333333331
[['dp_black_avg', 0.14300000000000002, 0.17900000000000005, 0.25], ['undersampling', -0.035999999999999976, 0.0, 0.0], ['smote', 0.0, 0.03600000000000003, 0.0], ['dp_asian_avg', 0.07399999999999995, 0.07399999999999995, 0.07399999999999995], ['undersampling', 0.07399999999999995, 0.18499999999999994, 0.18499999999999994], ['smote', 0.07399999999999995, 0.07399999999999995, 0.18499999999999994], ['dp_age30_avg', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334], ['undersampling', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334], ['smote', 0.1113333333333334, 0.1113333333333334, 0.1113333333333334], ['dp_age90_avg', 0.17466666666666675, 0.15166666666666673, 0.1286666666666667], ['undersampling', -0.007333333333333303, -0.030333333333333323, 0.08366666666666667], ['smote', 0.015666666666666718, -0.030333333333333323, -0.07533333333333331]]

In [98]:
# rows represent: [black, asian, age<30 and age>90]
df_full = pd.DataFrame(full_list)
df_transpose = df_full.T

In [99]:
df_transpose.to_csv('fig_6_recall_diff_comparison.csv')

# Radial bar plot numbers

In [36]:
from os import listdir
from os.path import isfile, join
import fnmatch
import pandas as pd


# *************** change dp name in the following line ******************** 
models = ['dp_age30_avg', 'dp_black_avg', 'dp_asian_avg', 'dp_age4050_avg', 'dp_age90_avg', 'dp_hispanic_avg']
indices = [7,4,6,9,14,5]
Groups = ['Age<30', 'Black', 'Asian', 'Age [40, 50)', 'Age>=90', 'Hispanic']


metric_idx = 2 #F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13

In [37]:
full_list = []
i=0
for mod in models:
    model_path = r"csv_files/"+ mod + "/test/"

    # take the csv files in that directory
    
    files = [f for f in listdir(model_path) if fnmatch.fnmatch(f, '*result_temp_*.csv')]
    
    for file in files:
        
        df = pd.read_csv(model_path  + file)
        values = df.iloc[indices[i],metric_idx]
    
        full_list.append([Groups[i], values])
    
    i=i+1
    

df_full = pd.DataFrame(full_list, columns= ["Group", "DP"])
print(df_full)

           Group     DP
0         Age<30  0.667
1         Age<30  0.667
2         Age<30  0.667
3          Black  0.643
4          Black  0.679
5          Black  0.750
6          Asian  0.778
7          Asian  0.778
8          Asian  0.778
9   Age [40, 50)  0.515
10  Age [40, 50)  0.606
11  Age [40, 50)  0.636
12       Age>=90  0.682
13       Age>=90  0.659
14       Age>=90  0.636
15      Hispanic  0.875
16      Hispanic  0.875
17      Hispanic  0.875

In [38]:
df_full.to_csv('fig_7_recall_comparison_DP.csv')

In [39]:
#loading original
model_path_original = r"csv_files/original/modify_threshold_moving/test/"


models = ['age30_thr_temp', 'black_thr_temp', 'asian_thr_temp', 'age4050_thr_temp', 'age90_thr_temp', 'hispanic_thr_temp']
indices = [7,4,6,9,14,5]
Groups = ['Age<30', 'Black', 'Asian', 'Age [40, 50)', 'Age>=90', 'Hispanic']


metric_idx = 2 #F1_C1 = 5 ; Rec_C1 = 2 ; bal_acc = 11; MCC = 13

In [40]:
full_list = []
i=0
for mod in models:
    model_name = r'*result_'+mod+'*.csv'
    #model_name = '*FINAL_aggregated*'
    print(model_name)
    files = [f for f in listdir(model_path_original) if fnmatch.fnmatch(f, model_name)]
    
    for file in files:
        df_original = pd.read_csv(model_path_original  + file)
        values_original = df_original.iloc[indices[i],metric_idx]
    
        full_list.append([Groups[i], values_original])
    
    i=i+1
    

df_full = pd.DataFrame(full_list, columns= ["Group", "Original"])
print(df_full)

*result_age30_thr_temp*.csv
*result_black_thr_temp*.csv
*result_asian_thr_temp*.csv
*result_age4050_thr_temp*.csv
*result_age90_thr_temp*.csv
*result_hispanic_thr_temp*.csv
           Group  Original
0         Age<30     0.000
1         Age<30     0.333
2         Age<30     0.333
3          Black     0.179
4          Black     0.286
5          Black     0.321
6          Asian     0.444
7          Asian     0.444
8          Asian     0.444
9   Age [40, 50)     0.636
10  Age [40, 50)     0.667
11  Age [40, 50)     0.545
12       Age>=90     0.636
13       Age>=90     0.727
14       Age>=90     0.705
15      Hispanic     0.875
16      Hispanic     0.750
17      Hispanic     0.875

In [41]:
df_full.to_csv('fig_7_recall_comparison_original.csv')